//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.23 at 09:37:29 PM AST 
//


package com.vehiclerecognition.soap.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vehiclerecognition.soap.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vehiclerecognition.soap.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchKeyResponse }
     * 
     */
    public SearchKeyResponse createSearchKeyResponse() {
        return new SearchKeyResponse();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link SearchKeyRequest }
     * 
     */
    public SearchKeyRequest createSearchKeyRequest() {
        return new SearchKeyRequest();
    }

    /**
     * Create an instance of {@link SearchCriteriaRequest }
     * 
     */
    public SearchCriteriaRequest createSearchCriteriaRequest() {
        return new SearchCriteriaRequest();
    }

    /**
     * Create an instance of {@link SearchCriteriaResponse }
     * 
     */
    public SearchCriteriaResponse createSearchCriteriaResponse() {
        return new SearchCriteriaResponse();
    }

}
