//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.23 at 11:06:01 PM AST 
//


package com.vehiclerecognition.soap.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vehicleClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="vehicleClass">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Otomobil"/>
 *     &lt;enumeration value="Otobüs"/>
 *     &lt;enumeration value="Arazi,SUV&amp;Pick-up"/>
 *     &lt;enumeration value="Kamyon,Kamyonet"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "vehicleClass")
@XmlEnum
public enum VehicleClass {

    @XmlEnumValue("Otomobil")
    CAR("Otomobil"),
    @XmlEnumValue("Otob\u00fcs")
    BUS("Otob\u00fcs"),
    @XmlEnumValue("Arazi,SUV&Pick-up")
    SUV("Arazi,SUV&Pick-up"),
    @XmlEnumValue("Kamyon,Kamyonet")
    TRUCK("Kamyon,Kamyonet");
    private final String value;

    VehicleClass(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VehicleClass fromValue(String v) {
        for (VehicleClass c: VehicleClass.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
