//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.23 at 09:37:29 PM AST 
//


package com.vehiclerecognition.soap.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vehicleClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="vehicleClass">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CAR"/>
 *     &lt;enumeration value="BUS"/>
 *     &lt;enumeration value="SUV"/>
 *     &lt;enumeration value="TRUCK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "vehicleClass")
@XmlEnum
public enum VehicleClass {


    /**
     * Otomobil
     * 
     */
    CAR,

    /**
     * Otobüs
     * 
     */
    BUS,

    /**
     * Arazi,SUV,Pick-up
     * 
     */
    SUV,

    /**
     * Kamyon,Kamyonet
     * 
     */
    TRUCK;

    public String value() {
        return name();
    }

    public static VehicleClass fromValue(String v) {
        return valueOf(v);
    }

}
